version: '3.9'

services:
  app:
    build: .
    container_name: user_management_app
    ports:
      - "80:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserManagementDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    restart: unless-stopped
    command: >
      sh -c "dotnet UserManagementApp.dll checkdb &&
      dotnet ef database update &&
      dotnet UserManagementApp.dll"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P Your_password123 -Q \"SELECT 1\" || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  sqlserver_data: